Fix TS error on `icon` prop of `ProductSwitcher` component
fixes this TS error `components/global/product_switcher.tsx:105:17 - error TS2322: Type '"view-grid-outline"' is not assignable to type 'TIconGlyph'.

105                 icon={'view-grid-outline'}
                    ~~~~

  node_modules/@mattermost/compass-components/components/icon-button/IconButton.props.d.ts:8:5
    8     icon: TIconGlyph;
          ~~~~
    The expected type comes from property 'icon' which is declared here on type 'IntrinsicAttributes & PIconButton & RefAttributes<HTMLButtonElement>'`